## Introduction

<!---start met het overkoepelende probleem dat centraal staat: (gender) inequality in academia. de Y--->

Gender disparities in academic careers are persistent and well-documented [e.g., @barrios2013; @bol2023; @greska2023; @kim2022; @lutter2016]. Women earn lower salaries, secure fewer grants, receive less recognition for innovative work, and experience shorter, less prolific careers compared to men [@hofstra2020; \@kim2024; @mulders2024; @tolsma2025]. They are also more likely to work on topics that yield lower career returns [@kim2024]. Inequality in academia is not limited to gender. Minoritized scholars - by national origin, ethnic background, or skin color - face similar barriers, including slower career progression and underrepresentation in senior positions [@hofstra2020; @kozlowski2022; @whittington2018]. First-generation scholars, too, often struggle to navigate the academic environment, slowing their advancement within academia.

<!--al veel bekend--->

The mechanisms perpetuating these inequalities are increasingly understood, ranging from biases in selection and promotion committees, overt discrimination and hidden micro aggression on the work floor leading to a chilly climate, to institutional policies (e.g. regarding parental leave) and differences in work preferences (e.g. differences in preferred discipline, or team science). Progress has been made in some areas. In the Netherlands, the current site of study, for example, targeted policies have reduced early-career disparities. Women and ethnic minority scholars are now as likely as their peers to start a PhD and after their PhD to continue in academia. Early-career grant gaps have narrowed, and more women are reaching the professorial ranks. This does not mean that gender inequality in (Dutch) academia is just a matter of time. Pay gays widen quickly after the PhD-stage and women are still more likely than men to leave academia before the retirement age and do so earlier in their career. This 'leaking pipeline' not only widens pay gaps but also perpetuates the persistent underrepresentation of women at the highest levels of academia. Inequality in Dutch academia, it seems, becomes most pronounced after the early career stages. <!---hiermee sorteer ik voor op BH's PhD interacties --->

<!--introductie onze angle via trechtermodel--->

In this contribution, we argue that a critical yet overlooked factor in academic inequality - one that could become especially relevant after early career stages - are social networks. In labor market and health inequality research, social networks are often seen as both a potential buffer against and a catalyst for inequality. Disadvantaged groups may use networks to compensate for resource deficits, but more commonly, networks exacerbate inequality by concentrating social capital among the already privileged. In academia, knowledge production is inherently social. Journal papers are reviewed by (unanimous) peers. Departmental colleagues, disciplinary conferences, and varieties of academic committees are all central to academic norms and practices [@burt1998; @stark2020; @bourdieu1988]. Previous work demonstrated that access to prestigious academic positions depend on one’s mentors [@hofstra2022] <!---but see AM that supervisorteam do not have impact--->; that dissertation committees exhibit gender-homophilous tendencies in awarding cum laude graduate degrees [@bol2023]; and that the size and composition of co-authorship teams dictate whether papers are disruptive or consolidating in their findings [@wu2019]. Differences in academic socialization and the networks that one is able to build may therefore constitute a central pathway through which inequalities emerge and reproduce.

<!---arguments why we study co-authorship netwerks--->

Peer-reviewed papers are the essential form to contemporary academic knowledge production [@ref] and journal papers are still a main aspect of academic evaluation. Working together on papers dynamically shapes productivity and visibility [@abbasi2011; @ductor2015; @li2022; @moody2004; @newman2001; @wallace2012]. The average number of co-authors on papers is increasing [@ref] as team science is becoming increasingly the norm. (REFS). Being less able to build a network of (past) co-authors harboring 'scientific capital' (e.g. knowing the scientific ropes; possessing specific theoretical or methodological knowledge, having access to funds, data or research assistants, team science skills, etc.) may leave long-lasting negative effects on academic careers. Differences in these co-author networks - whether in size, structure, socio-demographic composition, or the scientific capital they harbor - may not only contribute to further inequality, they are by itself, also an important form of inequality within academia. In this contribution, we therefore set out to explain the following central question: *How do co-authorship networks evolve, and how do these dynamics differ by gender?* By answering this, we aim to deepen our understanding of the mechanisms driving gender inequality in academia and to contribute to solutions that work towards improving equality.

<!---site of study--->

Our empirical setting is the Netherlands, where we analyze the co-authorship networks of all sociologists and political scientists employed at Dutch universities between 2022 and 2025 (N=...). We selected these disciplines for four reasons: first, much of the literature on academic inequality focuses on STEM fields, leaving social sciences understudied; second, both disciplines have near gender parity at the PhD level, allowing us to compare network dynamics across gender; third, their research outputs are predominantly multi-authored, international journal articles - and not monographs, patents, or publications in Dutch -, enabling reliable network construction, and fourth, we assume that co-authorship networks in these fields are largely domestic, making our data more comprehensive (i.e. capturing the large majority of co-authorships) than would we have selected more internationally oriented disciplines like anthropology or physics. Moreover, a focus on a limited set of disciplines makes it manageable to model the evolution of the co-authorship networks while allowing for (gender differences in) cross-disciplinary and cross-university collaborations.

<!---naar type verklaringen--->

To model network evolution, we draw on social network theory. We will take into account endogenous structural network effects that commonly drive network evolution for (positive) relations, such as reciprocity, triadic closure, preferential attachment and brokerage [@barabasi1999; @bojanowski2020; @ebadi2015; @gondal2011; @gondal2018] and have have found to be relevant in collaboration networks as well [@gao2022; @kwiek2021; @whittington2024; @hancean2014]. Choice homophily, the preference to form relations with people who are similar to us, is quite ubiquitous in social life. We therefore also take into account how similarity between scholars with respect to socio-demographic characteristics such as gender and migration background drive network dynamics. Next to socio-demographic dyadic similarity we include dyadic similarity related to the university scholars work at, their main discipline, and their specific research topics. These factors may impact preferences for collaboration but certainly also shape collaboration opportunities. Our primary focus, however, is on how scholar-level characteristics such as career stage, productivity, past network, and prestige, affect attractiveness as a co-author, and whether these 'scientific capital indicators' are valued differently for men and women. Our general hypothesis is that women’s scientific capital is systematically undervalued compared to men’s, contributing to persistent gender inequality in academic networks.

<!---onze methode introduceren. hiervoor nodig om def van netwerk te geven--->

How to define and consecutively operationalize a co-author-relation is not self-evident. Scholars may work together on a paper, but contribute in different ways and have different roles. Similarly, when putting together the team of co-authors, not all scholars will have had to same agency, not in proposing potential collaborators, nor in refusing received 'invitations'. To contruct our co-authorship networks we rely on the journal papers of our scholars in our sample (....unique papers). Based on this, we constructed two *directed* co-authorship networks: one in which we considered the first author as the one sending ties to all other co-authors, and one where we take the last author as the one sending ties to all others, combining them into a multiplex network to analyze both layers jointly. While, our data at the tie-level is time-stamped (i.e. the publication data of the paper), we aggregated our network data to three two-year time windows, because we collected scholar-level data only at three time points (...) and to reflect that that co-authorships signal collaboration *relations* and are not short-term *events*. We binarized the networks (i.e. yes/no tie), because they were already quite sparse (with densities below 5%??) and we observed only few multiple co-authorship occasions between the same scholars (percentage?) in the same time-window. This operationalization allows us to analyze the evolution of co-authorship networks via the Stochastic Actor Orientated Model as implemented in the R package RSiena. We will briefly discuss alternative approaches in our discussion section.

Our study contributes the literature on inequality in academia in several ways. We introduce a social network perspective, treating co-authorship networks as both a site and a driver of inequality. We move beyond descriptive analyses and investigate how these networks develop differently for men and women. We do so by drawing from comprehensive data on the near-population of sociology and political science scholars in Dutch universities between (year and year) and their co-authorship histories. We thus reduced the influence of survivor and publication bias that commonly distorts conventional bibliometric network studies [@simko2015] with a focus on highly productive scholars or the output published within specific selected journals [@hancean2014; @ossenblok2014]. In our theoretical framework we not only take into account structural network effects and that scholars may have different opportunities for collaboration and exert different preferences but importantly, we also assess the extent to which scientific capital indicators shape networks differently for men and women. We analyze the evolution of co-authorship networks with state of art social network techniques. Finally, our dataset is made publicly available for the scientific community on the replication website that accompanies this contribution ... .

## Theory

<!---wellicht hier al kort wat we al weten uit de literatuur. publiceren minder, kleinere netwerken.vaker team science, dus grotere netwerken. -->

<!---ik dacht dat we dan theoriesectie wellicht kunnen beginnen met wat we al descriptief weten over de ongelijkheid hierin--->

Women’s collaborations are also more often local and not international [@kwiek2021], and they populate fewer senior authorship positions [@barrios2013]. Furthermore, scholars with minoritized nationalities tend to occupy peripheral network positions [@hancean2014; @khor2016; @kim2016; @kwiek2021], limiting exposure to high-impact journals and influential collaborators. Origin-based disadvantages are reinforced by institutional prestige hierarchies [@allison1987; @allison1990; @wapman2022]: work from elite universities and English-speaking or Western countries is more likely to be indexed, cited, and recognised [@khor2016; @li2022], while research from less visible institutions or non-core regions is underrepresented [@cespedes2025; @zheng2025]. Prior work shows that women are less likely than men to occupy powerful positions in (co-authorship) networks [@gao2022; @whittington2018; @whittington2024].

<!---alinea met eigen statistieken--->

In the Netherlands, PhD-students are part of the staff of the department and expected to write 3 to 5 journal papers as part of their dissertation, which generally takes approximately 4 years. The common practice in the Netherlands, and at least so within the disciplines of sociology and political science, is that the PhD, who is doing the majority of work, becomes the first author and the promoter the last author; sole authored papers by PhDs are rare. Middle authors may be added when, for example, the supervision team consists of multiple (co-)promotores, or when experts are added to the team, commonly on the initiative of the promoter. Thus during a PhD-project, <!---eigenlijk ook bij postdocs of niet?---> it is predominantly the promoter (the last author) who creates the collaboration ties ('invites' others to collaborate). Dynamics become quite different outside PhD-projects among more senior faculty members (assistant, associate and full professors). Here, we assume that the initiative could also be taken by the scholar who ends up as first author and not necessarily by the most senior scholar. Thus when we will theorize on network dynamics (and gender differences herein), we should be aware of the special position PhD students are in.

Here, we build on earlier insights and examine to what extent network mechanisms – such as homophily, triadic closure, preferential attachment, and brokerage – shape collaboration opportunities and inequalities [@barabasi1999; @bojanowski2020; @ebadi2015; @gondal2011; @gondal2018] and reproduce gender and origin-based segregation in collaboration networks [@gao2022; @kwiek2021; @whittington2024; @hancean2014]. Therefore, we ask: *to what extent are there gender- and origin-based differences in collaboration (networks)?* and *to what extent are there gender- and origin-based differences in homophily? Do actors tend to choose collaborators who share their gender or origin?* We do so by drawing from comprehensive data on a near-population of social scientists in Dutch universities and their co-authorship histories. These time-stamped snapshots function as an ankerpoint in each scholar’s career, fixing their affiliation and co-authorships at a given moment in time and thereby reducing the influence of survivor and publication bias that typically distort conventional bibliometric network studies [@simko2015]. This allows us to characterize disparities in collaboration opportunities and outcomes not just for a selected discipline or journal, but for the entire social-science habitat, mirroring recent full-population approaches in the science-of-science literature [@hofstra2020; @whittington2024]. Prior work interprets gender or origin gaps in collaboration without fully considering network endogenous processes such as transitivity [@gao2022; @kwiek2021], possibly overestimating key indicators like homophily. Here, we are among the first to explicitly model path dependency and endogenous network processes such as transitivity by using longitudinal network models. This shifts the focus from descriptive differences to the network processes through which inequalities are reproduced. Because our data provide rich information on all actors in the network and approximate a full-population sample, we can also address survivor bias and sample selection problems

We also posit that gender- and origin-based differences in collaboration do not happen in a vacuum and introduce the idea of intersectionality in academic collaboration networks. This provides a framework for understanding how axes of inequality intersect, emphasizing that gender and origin (or race, ethnicity, nationality) are mutually constitutive axes of social stratification [@crenshaw1989; @king1988]. This is important, because prior work in science and higher education for instance demonstrates that gender penalties tend to be more pronounced for women from underrepresented nationalities or ethnic groups, while shared nationality may mitigate disadvantages for majority-group women – or vice versa [@kwiek2021; @vanderwal2021]. Approaches that simply consider gender and origin therefore understate the disadvantage that accrues at their intersection and risk missing the specific penalties experienced by intersectional groups [@kozlowski2022]. Therefore, we are among the firs to explicitly contribute an intersectional perspective to study collaboration opportunities and segregation in collaboration networks among Dutch social scientists. This enables us to ask and answer novel questions, for instance on whether homophily on gender and origin is stronger for majority-group men than for minoritised scholars, whether international women are particularly excluded from triadic closure processes, and whether bridging ties to high-status alters are unequally distributed [@kwiek2021; @whittington2024]. By focusing on these mechanisms by means of our intersectional perspective, we identify in far more detail than before where in the collaboration process intersectional penalties emerge. Therefore, we ask: *to what extent does gender- and origin-based homophily intersect? Do actors tend to choose collaborators who share both their gender and their origin?*

Finally, we examine the role of social connections in academic networks even further by explicitly studying second order social capital influences. This refers to the resources and opportunities people can access through the contacts of their contacts. This type of capital may be particularly relevant in academic networks because introductions to influential collaborators, invitations to special issues, or access to well-funded research teams may arise from the networks of mentors, co-authors, or departmental colleagues. Women and minoritized scholars may be less likely to benefit from the indirect networks of their advisors or collaborators. As a result, inequalities compound across network levels, making second-order social capital a key mechanism through which gender, origin, and intersectional disparities in collaboration emerge. To our knowledge, such questions have hardly been asked in the context of co-authorship networks despite reasonable assumptions that such an approach offers us far more insight into how unequal access to high-status, well-connected, and highly productive alters-of-alters shapes cumulative advantage and disadvantage in academic careers. We therefore study to what extent network aspects of second-order social capital - in particular the h-index, degree centrality, and academic position – operate differently across gender and origin groups and their intersection?

::: callout-note
RQ4 nog nader bij te stellen na overleg over welke variabelen we hierin willen benadrukken.

Allen: welke maat vinden jullie hierbij het beste passen?
:::

```{=html}
<!-- 
Om het te kunnen publishen in ESR moet er wel een duidelijker sociaal probleem te zijn.
-->
```
