project:
  type: website
  output-dir: docs
  execute-dir: project

website:
  title: "Networks"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - text: Documentation
        menu:
        - href: src/docs/content/create_scholars.qmd
          text: Create Scholars
        - href: src/docs/content/process_names.qmd
          text: Process Names
        - href: src/docs/content/process_gender.qmd
          text: Process Gender
        - href: src/docs/content/process_ethnicity.qmd
          text: Process Ethnicity
        - href: src/docs/content/scrape_authorid.qmd
          text: Scrape Author ID using `openalexr`

# execute:
#   freeze: true

format:
  html:
    theme: cosmo
    css: src/docs/styles.css
    toc: true
    code-line-numbers: true
    code-annotations: true
    df-print: paged



