project:
  type: website
  output-dir: docs
  execute-dir: project
  render:
    - index.qmd
    - src/code/*.qmd
    - src/code/
  post-render:
    - src/utils/rename_old_datafiles.R

website:
  title: Networks
  navbar:
    left:
      - text: Data Processing
        menu:
          - href: src/code/01.create_scholars.qmd
            text: Create Scholars
          - href: src/code/02.process_names.qmd
            text: Process Names
          - href: src/code/03.process_gender.qmd
            text: Process Gender
          - href: src/code/04.process_ethnicity.qmd
            text: Process Ethnicity
      - text: Data Scraping
        menu:
          - href: src/code/05.scrape_openalex.qmd
            text: Scrape Information from OpenAlex
          - href: src/code/06.combine_data.qmd
            text: Combine OpenAlex data
          - href: src/code/07.clean_data.qmd
            text: Data Cleaning
          - href: src/code/08.process_affiliations.qmd
            text: Process Affiliations
      - text: Analyses
        menu:
          - href: src/code/09.descriptive_analysis.qmd
            text: Descriptive Analyses
    right:
      - text: Utilities
        menu:
          - href: src/code/0a.custom_functions.qmd
            text: Custom Functions
      - icon: github
        href: https://github.com/jossl95/co-pub_networks/tree/main
        aria-label: GitHub
  
        
# execute:
#   freeze: true

format:
  html:
    theme: cosmo
    css: src/code/styles.css
    toc: true
    code-line-numbers: true
    code-annotations: true
    df-print: paged

excluded:
  - papers/



