project:
  type: website
  output-dir: docs
  execute-dir: project

website:
  title: Networks
  navbar:
    left:
      # - href: index.qmd
      #   text: Home
      - text: Data Processing
        menu:
          - href: src/docs/content/create_scholars.qmd
            text: Create Scholars
          - href: src/docs/content/process_names.qmd
            text: Process Names
          - href: src/docs/content/process_gender.qmd
            text: Process Gender
          - href: src/docs/content/process_ethnicity.qmd
            text: Process Ethnicity
      - text: Data Scraping
        menu:
          - href: src/docs/content/scrape_authorid.qmd
            text: Scrape Author ID using `openalexr`
          - href: src/docs/content/scrape_works.qmd
            text: Scrape Works using `openalexr`
          - href: src/docs/content/combine_data.qmd
            text: Combine Scrape data
    right:
      - icon: github
        href: https://github.com/jossl95/co-pub_networks/tree/main
        aria-label: GitHub
  
        
execute:
  freeze: true

format:
  html:
    theme: cosmo
    css: src/docs/styles.css
    toc: true
    code-line-numbers: true
    code-annotations: true
    df-print: paged



