project:
  type: website
  output-dir: docs

website:
  title: "Networks"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - text: Documentation
        menu:
        - href: src/docs/content/create_scholars.qmd
          text: Create Scholars


format:
  html:
    theme: cosmo
    css: src/docs/styles.css
    toc: true



