project:
  type: website
  output-dir: docs
  execute-dir: project
  post-render:
    - src/utils/rename_old_datafiles.R

website:
  title: Networks
  navbar:
    left:
      - text: Data Processing
        menu:
          - href: src/code/create_scholars.qmd
            text: Create Scholars
          - href: src/code/process_names.qmd
            text: Process Names
          - href: src/code/process_gender.qmd
            text: Process Gender
          - href: src/code/process_ethnicity.qmd
            text: Process Ethnicity
      - text: Data Scraping
        menu:
          - href: src/code/scrape_openalex.qmd
            text: Scrape information from OpenAlex
          - href: src/code/combine_data.qmd
            text: Combine OpenAlex data
    right:
      - icon: github
        href: https://github.com/jossl95/co-pub_networks/tree/main
        aria-label: GitHub
  
        
# execute:d
#   freeze: true

format:
  html:
    theme: cosmo
    css: src/code/styles.css
    toc: true
    code-line-numbers: true
    code-annotations: true
    df-print: paged



