project:
  type: website
  output-dir: docs
  execute-dir: project
  render:
    - index.qmd
    - src/code/*.qmd
    - src/code/
  post-render:
    - src/utils/rename_old_datafiles.R

website:
  title: Networks
  navbar:
    left:
      - text: Data Processing
        menu:
          - href: src/code/01.create_scholars.qmd
            text: Create Scholars
          - href: src/code/02.process_names.qmd
            text: Process Names
          - href: src/code/03.process_gender.qmd
            text: Process Gender
          - href: src/code/04.process_ethnicity.qmd
            text: Process Ethnicity
      - text: Data Scraping
        menu:
          - href: src/code/05.scrape_openalex.qmd
            text: Scrape Information from OpenAlex
      - text: Data Preparation
        menu:
          - href: src/code/06.combine_data.qmd
            text: Combine OpenAlex data
          - href: src/code/07.clean_data.qmd
            text: Data Cleaning
          - href: src/code/08.process_topics.qmd
            text: Process Topics
          - href: src/code/09.operationalizations.qmd
            text: Operationalizations
      - text: Analyses
        menu: 
          - href: src/code/10.descriptives.qmd
            text: Descriptive Analysis
          - href: src/code/11.visualization.qmd
            text: Network Visualization
          - href: src/code/12.net_descriptives.qmd
            text: Network Descriptive Analysis
          - href: src/code/13.main_analyses.qmd
            text: Main Analyses
         
    right:
      - icon: github
        href: https://github.com/jossl95/co-pub_networks
        aria-label: GitHub
  page-footer: 
    center: "Copyright © 2026 | Jos Slabbekoorn"
  back-to-top-navigation: true
  

execute:
  # freeze: true
  warning: false

format:
  html:
    # css: src/code/styles.css
    toc: true
    code-line-numbers: true
    code-annotations: true
    df-print: paged
    respect-user-color-scheme: true

    theme:
      light: [cosmo, src/theme.scss]
      dark: [cosmo, src/theme.scss, src/theme-dark.scss]
    highlight-style: arrow

excluded:
  - papers/

resources: papers/_output/paper1.pdf



