project:
  type: default
  render: 
    - "paper1.qmd"
  output-dir: _output    # <-- all rendered files go here

execute:
  freeze: auto

bibliography: assets/references.bib
csl: assets/apa.csl

format:
  hikmah-pdf:
    papersize: a4
    geometry:
      - top=30mm
      - left=30mm
      - bottom=30mm
      - right=30mm
    number-sections: true
    number-depth: 3
    linestretch: 1.5

  hikmah-manuscript-docx:
    papersize: a4
