---
title: "Gender inequality in co-authorship networks in Dutch academia"


code-repo: "Access the code, data, and analysis at <https://github.com/jossl95/co-pub_networks>"
correspondence-prefix: "Correspondence concerning this article should be addressed to"

author: 
  - name: "Bas Hofstra"
    orcid: 0000-0002-9052-956X
    affiliations:
      - ref: RU
  - name: "Jos Slabbekoorn"
    orcid: 0000-0001-8419-5703
    #email: jos.slabbekoorn@ru.nl
    affiliations: 
      - id: RU
        name: Radboud University Nijmegen
        department: Sociology
        country: The Netherlands
  - name: "Roza Meuleman"
    orcid: 0000-0002-4486-253X
    affiliations:
      - ref: RU
  - name: "Jochem Tolsma"
    orcid: 0000-0002-4411-6932
    email: jochem.tolsma@ru.nl
    affiliations:
      - ref: RU
      - id: RUG
        name: University of Groningen
        department: Sociology
        country: The Netherlands
    attributes:
      corresponding: true

date: today

excluded:
  - paper1/_archive

keywords: 
   - Gender inequality in academia
   - Co-Authorship Networks
   - Scientific capital
   - Social network analysis
bibliography: references.bib
---

## Introduction

<!--# worsteling: scientific capital is nu ook gedefinieerd op het individuele niveau (mijn i-index, mijn positie) en niet enkel op het (egocentric) co-authorship network niveau. Dat is eigenlijk vreemd, want we willen het social network perspective centraal stellen. scientific capital centraal stellen, maar wmb eigenlijk vooral scientific capital embedded in networks. Oplossing, social scientific capital -->
<!---# of scientific social capital ?---?
<!--- RM: zou kiezen voor personal(ego) vs. social (alter) scientific capital - ook in te bedden als embodied vs. accessed capital, toegevoegd---> 


Gender disparities in academic careers are persistent and well-documented [e.g., @barrios2013; @bol2023; @cairo2026; @greska2023; @kim2022; @lutter2016]. Women earn lower salaries, secure fewer grants, receive less recognition for innovative work, and experience shorter, less prolific careers compared to men [@hofstra2020; @kim2024; @mulders2024; @tolsma2025]. They are also more likely to work on research topics and innovations that yield lower career returns [@hofstra2020; @kim2024]. Such inequalities in academia are not limited to gender. <!--- Minoritized scholars - by national origin, ethnic background, or skin color - face barriers as well, including those that slow career progression to senior academic positions [@hofstra2020; @kozlowski2022; @whittington2018]. ---> <!--- RM: status van migratie achtergrond onduidelijk - hangt er nu een beetje bij - wmb naar controle = meer focus, BH: eens, zin kan weg. --->  
<!--- kan weg: First-generation scholars, too, often struggle to navigate the academic environment, slowing their advancement within academia. --->

<!--al veel bekend--->

The mechanisms causing these gender inequalities are increasingly understood. They range from biases in selection and promotion committees, overt discrimination and hidden micro aggressions leading to chilly lab or office climates for women <!--- and minoritized persons--->, to discriminatory institutional policies (e.g. regarding parental leave) and differences in work preferences (e.g. differences in preferred discipline, or team science prevalence). In some areas there have been some strides toward equity. In the Netherlands, the current empirical site, for example, targeted policies have reduced early-career disparities. Women <!--- and ethnic minority ---> scholars are now as likely as their peers to start a PhD and women increasingly transition to faculty positions. As such, early-career grant gaps have narrowed, and more women are reaching professorial ranks. Yet, this does not mean that gender equality in (Dutch) academia is only a matter of time. Pay gaps widen quickly after the PhD-stage and women are still more likely than men to leave academia earlier in their career [@mulders2024; @cairo2026]. This 'leaky pipeline' not only widens pay gaps but also perpetuates the persistent underrepresentation of women at the senior positions in academia. Gender inequality in (Dutch) academia, it seems, becomes most pronounced after the early career stages. <!---hiermee sorteer ik voor op BH's PhD interacties Bas: nice; RM: zie ook cairo2026 --->

<!--introductie onze angle via trechtermodel--->

In this study, we argue that a critical yet relatively overlooked factor in academic gender inequality -- and one that becomes especially relevant after early career stages -- are social networks. Social networks are often seen as both a potential buffer against and a catalyst for labor market inequality [@aguilera2008; @blommaert2020; @collischon2021; @lutter2015; @meuleman2026; @woehler2021]. Disadvantaged groups may use networks to compensate for resource deficits, but more commonly, networks exacerbate inequality by distributing power to the privileged, reproducing existing hierarchies. Such processes are likely in academia as well, as knowledge production is inherently social. Journal papers are reviewed by (unanimous) peers. Departmental colleagues, disciplinary conferences, and varieties of academic committees are all central to academic norms and practices [@burt1998; @stark2020; @bourdieu1988]. Additionally, previous work demonstrated that access to prestigious academic positions depend on one’s mentors [@hofstra2022] <!---but see AM that supervisorteam do not have impact, BH: better direct measures in my paper--->; that dissertation committees exhibit gender-homophilous tendencies in awarding cum laude graduate degrees [@bol2023]; that the size and composition of co-authorship teams dictate whether papers are disruptive or consolidating in their findings [@wu2019]; and with women’s promotions generating spillovers in the representation of women among PhD graduates and faculty, as well as in their retention in academia [@bagues2026]. Women professors themselves explicitly document the lack of recognition of women, implicit bias in evaluations, male networks and an unwelcoming academic culture as explanations for gender disparities in academia [@Jarvinen2026]. Thus, the access to and returns of scientific networks constitute a central pathway for the genesis en reproduction of inequalities.

<!---arguments why we study co-authorship netwerks--->
Co-authors are among the key social relationships in academics' careers: peer-reviewed papers with co-authors are the essential form to contemporary academic knowledge production [@ref] and journal papers are still a main aspect of academic evaluation. Working together on papers dynamically shapes productivity and visibility [@abbasi2011; @ductor2015; @li2022; @moody2004; @newman2001; @wallace2012]. The average number of co-authors on papers is increasing [@refDAHSUNWNAG?] as team science is increasingly common. Being less able to connect to and sustain (past) co-authors harboring 'scientific capital' leaves long-lasting negative effects on academic careers. It implies less access to co-authors with team science skills, complementary theoretical or methodological knowledge, who have access to funds, data or research assistants. Differences in these co-author networks – whether in size, structure, or composition – may not only contribute to further inequality, they are by themselves a potential source of inequality in academia. In this contribution, we therefore set out to answer the following central question: <!--- (1) *To what extent do co-authorship differ by gender?* and (2) ---> *How do co-authorship networks evolve over time, and how do these dynamics differ by gender?* <!--- Our first research question takes a *static* perspective, while the second deals with the *evolution* of co-authorship networks formed by a population of scholars in our study. This is intentional, as answering both questions in tandem, ---> By answering this question we deepen our understanding of the degree of, and the mechanisms driving gender disparities in academia. 

<!---site of study--->

Our empirical setting is the Netherlands, where we analyze the co-authorship networks of all sociologists and political scientists employed at Dutch universities between 2022 and 2025 (N=1.175). We selected these disciplines for various reasons. <!--- first, much of the literature on academic inequality focuses on STEM fields, leaving social sciences understudied; <!--- BH: sociology is perhaps the most studied field in history, by sociologists, so I'll remove this one. --->  First, both disciplines have near gender parity at the PhD level [@refs], providing us with a strict test and allowing a comparison of network dynamics across genders. Second, the research outputs in both disciplines are predominantly multi-authored, international journal articles – and not monographs, patents, or publications in Dutch –, enabling reliable network construction. Third, we assume that co-authorship networks in these fields are largely domestic, making our data more comprehensive (i.e. capturing the large majority of co-authorships) than would we have selected more internationally oriented disciplines like anthropology or physics. Lastly, the focus on a limited set of disciplines makes it manageable to model the evolution of the co-authorship networks while allowing for (gender differences in) cross-disciplinary and cross-university collaborations. In sum, our empirical site is ideal for a in-depth study of complex network dynamics.

<!---naar type verklaringen--->
<!---RM: heb alinea herschreven, starten met meest vernieuwende en iets meer body proberen te geven aan de twee kapitaal vormen en de twee dynamics--->

Integrating insights from social capital theory and capital conversion [@bourdieu1986; @burt1998; @lin2001], we advance the literature by foregrounding a relatively underexamined mechanism: scientific capital. Adopting a Bourdieusian perspective, we examine how scholars’ *personal* (i.e. embodied) and *social* (i.e. accessed) scientific capital shape their attractiveness as collaborators, and whether these resources yield differential returns for men and women. Rather than emphasizing unequal access to scientific capital, we focus on its conversion into co-authorship ties. Specifically, we analyze how productivity, citation impact, and academic rank (i.e. personal scientific capital), and the size, structure, and composition of prior co-authorship networks (i.e. social scientific capital) influence tie formation, and whether these returns to personal and social scientific capital are gendered. We develop two competing expectations: a devaluation dynamic, whereby women’s contributions are discounted and yield weaker returns to equivalent scientific capital, and a compensatory dynamic, whereby women rely more heavily on observable signals of competence and connectedness, potentially deriving stronger returns. These mechanisms map onto broader processes of stratification: devaluation sustains the reproduction of inequality by lowering the returns to women’s capital, whereas compensatory dynamics point to a constrained form of mobility, in which women must leverage higher levels of capital to achieve comparable outcomes. By theorizing and testing these mechanisms jointly -- and across distinct forms of capital -- we move beyond prior work that examines them in isolation, offering a more precise account of how gender inequality is reproduced through collaboration dynamics.

<!--- bh: heel mooi --->

Empirically, we model the evolution of co-authorship networks using a social network perspetice. To isolate the returns to scientific capital, we account for baseline mechanisms of tie formation, including homophily by gender and other characteristics like migration background [@MCPHERSONS2001], as well as opportunity structures related to shared institutional affiliation, disciplinary proximity, and research topics. We further control for endogenous network dynamics—such as reciprocity, triadic closure, preferential attachment, and brokerage -- each of which are known to structure (collaboration) networks [@barabasi1999; @bojanowski2020; @ebadi2015; @gondal2011; @gondal2018; @gao2022; @kwiek2021; @whittington2024; @hancean2014]. This approach allows us to distinguish the effects of scientific capital from the broader network processes through which collaboration and (gender) inequalities emerge.

<!--- spoiler, komt later wel Our general hypotheses -- for which we will provide more argumentation in the next section -- are: (1) Women scholars possess less scientific capital than men, both personally as well as embedded in the co-authorship network; and (2) that women’s scientific capital is less likely to lead to co-authorships than men's, contributing to persistent gender inequality in academic networks.RM: ja later --->

<!---contributions--->

So given our empirical site and focus, our study contributes to the literature on inequality in academia in several ways. First, we contribute the concept of scientific social capital which scholars can either possess themselves *and* which is also sourced from their collaboration networks. We contribute a social network perspective, by treating co-authorship networks as both a potential site and a driver of gender inequality. We  compare differences in scientific capital by gender but also move beyond descriptive analyses by investigating how the complete network of co-authorships develops over time. We do so by drawing from comprehensive data on the near-population of sociology and political science scholars in Dutch universities (including PhD-students) between (2022 and 2025) and their co-authorship histories. We thus reduced the influence of survivor and publication bias that commonly distorts conventional bibliometric network studies [@simko2015] with a focus on highly productive (senior) scholars or the output published within specific selected journals [@hancean2014; @ossenblok2014]. When explaining network dynamics, we recognize the importance of structural network effects, and mechanisms related to preferences and opportunity structures. But importantly, we assess the extent to which scientific capital indicators shape networks differently for men and women. We model the evolution of the complete co-authorship network with the Stoachastic Actor Orientated Model as implemented in RSiena. With this, we are among the first to explicitly model path dependency and endogenous network processes using longitudinal network models, shifting the focus from mere descriptive differences to the network processes through which these inequalities emerge and are reproduced. Finally, our data set is made publicly available for the scientific community on the replication website that accompanies this contribution (WEBLINK).

<!--- I am unsure whether this entire last paragraph i necessary. Ik vond het goed lopen tot "type verklaringen" iets ge-edit, past nu beter--->
<!--- RM: wmb kan bovenstaande alinea weg - herhaling en data/methoden kan later--->
<!--- Bh: kan idd weg, te veel herhaling, alles is al gezegd en hier wordt het nog eens (minder helder) uit de doeken gedaan. kort eindigen met methodiek (eenalaatste para) mooier--->

## Theory

<!---onze methode introduceren. hiervoor nodig om def van netwerk te geven, dit wordt eerste alinea theorie--->

### Personal and social scientific capital
<!--- RM: theoretisch ingestoken vanuit capital conversion, fields als startpunt ---> <!--- RM: ik zou persoonlijk hiermee beginnen en bovenstaande twee alineas later; phd/pd omschrijven naar focus op ud-uhd  --->

Drawing on capital conversion [@bourdieu1986], we start from the premise that different forms of capital, e.g., economic, cultural, and social, can convert into each other. Rather than treating social networks as a departure point, this perspective conceptualizes them as the outcome of investments of other forms of capital. That is, building and sustaining relationships requires resources and individuals must be able to mobilize status, knowledge, and reputation to establish and maintain beneficial ties. In this view, inequalities in collaboration arise not only from differences in the possession of capital, but from differences in how effectively these resources are converted into network ties. Scientific collaboration can thus be understood as an outcome of capital conversion, where scholars are more or less successful in mobilizing their resources to form co-authorship ties. 

Which forms of capital are actually mobilized and valued in the academic *field*? Not all forms of capital are equally convertible into collaboration ties; their value depends on how they are recognized and rewarded in this specific academic context. Here, we put forward that *scientific capital* functions as a field-specific resource that can be converted into co-authorship ties. Following [@erices-ocampo2025], we theorize that scientific resources operate at different analytical levels. That is, they differ in *resource position*, i.e. where they are located and how they can be converted into capital. Some are embodied in individual scholars while others are embedded in and accessed trough the network relations. We make a distinction between personal and social scientific capital as particularly relevant to the formation of academic co-authorship ties.

*Personal scientific capital* refers to embodied, individual-level resources that scholars accumulate through their own academic trajectory -- consistent with Bourdieu’s notion of capital as incorporated dispositions and accumulated recognition. It includes indicators such as productivity, citation impact, and academic rank. These resources signal reputation and competence to potential collaborators and may shape how attractive a scholar is as a future co-author. 

*Social scientific capital* refers to relational, network-embedded resources that scholars accumulate through collaborations, consistent with Bourdieu’s view of capital as embedded in social relations. It encompasses both structural features of collaboration networks, such as size and density, and the resources embedded within them, such as the presence of cross-disciplinary ties. Being well-positioned in a dense, prestigious network signals access to knowledge and expertise, which may increase a scholar’s attractiveness as a potential co-author. Together, these two dimensions capture a bundle of assets that scholars bring to future collaborations. As such, we conjecture:

*Hypothesis 1: Scholars prefer to collaborate with counterparts possessing (a) personal and (b) social scientific capital.*
//
*Hypothesis 1: The higher scholars' (a) personal scientific capital and (b) social scientific capital, the more likely they are to form academic co-authorship ties.* 

### Structural devalution or a neccessary compensating strategy?
Resulting from an interplay between structural constraints in academia, gendered expectations, and gender homophily in collaboration processes, prior work has documented persistent gender differences in both embodied (personal) and accessed (social) scientific capital. Women scholars, on average, receive fewer grants, accumulate fewer citations, and are underrepresented in senior academic ranks compared to their men counterparts [BERTERE REFS HIER: Lerman et al. 2022; @hofstra2020; @mulders2024; @tolsma2025].  They also tend to publish less than men and occupy fewer senior authorship positions [@barrios2013; @tolsma2025], even if they contribute equally. In addition, women are less likely than men to occupy powerful positions in (co-authorship) networks [@gao2022; @whittington2018; @whittington2024], with their collaborations more often locally or nationally oriented rather than internationally oriented [@kwiek2021]. But rather than studying gender differences in access, we uniquely study the *gendered returns* to embodied (personal) and accessed (social) scientific capital. We ask whether equivalent levels of scientific capital translate into similar collaboration opportunities for men and women, or whether their conversion into co-authorship ties systematically differs by gender.

The direction of this gender asymmetry is theoretically ambiguous, and we distinguish hypotheses that move beyond a simple oppositional framing. A substantial literature documents the devaluation of women's contributions in science (e.g., for career progression, salary) [@hofstra2020; @kim2024]: the Matilda Effect (ROSSITER 1993). If evaluators discount the productivity, impact, or network positions of women scholars, then equivalent levels of scientific capital translates into fewer collaborative returns for women. Such devaluation of scientific capital may stem from implicit bias, where the image of a competent, achieving scientists is predominantly male, and women's contributions are attributed to luck rather than ability. This structural devaluation logic thus implies a gender penalty in the conversion of scientific capital into collaboration opportunities: identical resources yield lower returns for women.

At the same time, in response to well-documented barriers women face, scientific capital may also function as a compensatory resource in the conversion process. That is, women may need to signal their capital more strongly in order to be perceived as equally attractive collaborators. Under this logic, equivalent levels of capital yields stronger marginal returns for women, not because their capital is more highly valued, but because they have had to rely on it more heavily to overcome systemic barriers in access and visibility. In contrast, men might be able to rely more on (gendered beliefs about) their qualities and abilities regardless of their resources.

Importantly, these mechanisms of devaluation and compensation are unlikely to operate uniformly across both dimensions of scientific capital. Embodied and accessed scientific capital are evaluated through different mechanisms, and gender bias may operate more strongly in one dimension than in the other. Embodied scientific capital, including productivity, citation impact, career stage, may often be attributed to individual merit. This individual attribution renders it vulnerable to gendered devaluation as a substantial literature shows that evaluators systematically discount the personal contributions of women scholars when assessing the same outputs. These mechanisms relate to implicit biases that operates most  when judgments concern individual merit and competence, the domains where gender stereotypes are  activated. <!--- zit ewat redundantie in--->

Accessed scientific capital, by contrast, is relational and thus only partially reducible to individual merit. Network position, the prestige of co-authors, and cross-disciplinary ties reflect embeddedness in broader collaboration structures. Because these signals are jointly produced and publicly observable, they are less directly attributable to individual ability alone. A prestigious co-author is a prestigious co-author regardless of the gender of the scholar they collaborate with, and a large, dense network signals access to resources that prospective collaborators can observe and potentially benefit from. To the extent that accessed scientific capital functions as a signal of collaborative value based on *others*, it may be less susceptible to individual-level devaluation mechanisms affecting personal scientific capital. As such, it may provide a compensatory pathway through which women can partially offset disadvantages in the conversion of their personal scientific capital.

In sum, beyond the question of whether capital yields higher or lower returns for women, we consider a more nuanced possibility: that devaluation is not uniform but selective, operating through the mechanisms by which different types of capital are valued differently rather than through an overall discount on women scholars as collaborators. As such, we conjecture: 

*Hypothesis 2: Gender devaluation in collaboration is selective — (a) the scientific personal capital of women scholars is less likely to translate into academic co-authorship ties,  whereas (b) their scientific social capital is more likely to translate into academic co-authorship ties.*

### At what stage does gender inequality in academic careers unfold?

We adjudicate between these predictions empirically by estimating gender-specific effects of scientific personal and social capital on tie formation in stochastic actor-based models. How to theoretically define (and operationalize) a co-author-relation, however, is not self-evident. Scholars may work together on a paper, but contribute in different ways and occupy different team roles. Similarly, when putting together the team of co-authors, not all scholars will have had similar agency; not in proposing potential collaborators, nor in refusing received 'invitations'. To construct our co-authorship networks we rely on the journal papers of our scholars in our sample (....unique papers). Based on this, we constructed two *directed* co-authorship networks: one in which we take a 'first author perspective' in which the first author sends the co-author ties to all other co-authors, and one in which we take a 'last author perspective and take the last author as the one sending ties to all others co-authors. A first-author perspective may signal intellectual leadership and active co-author selection, whereas last authorship may reflect seniority, supervision, and convening collaborators. These roles carry different kinds of agency in shaping who works with whom, and they may even be distributed unequally across gender. Studying ties from both perspectives enables us to assess whether network dynamics and gender disparities manifest differently depending on the type of collaborative agency at stake.

We also consider whether returns to scientific capital by gender vary across career stage  This last point is important as the research sites in which we answer our questions are the disciplines of sociology and political sciences across the research universities in the Netherlands (if they have any such clearly delineated departments). In these disciplines, PhD students are often a cornerstone of a department's publishing activity, where dissertations are almost without exception a collection of (near) published papers, particularly so in the years we consider. Sociologists and political scientists in the Netherlands – PhDs and faculty alike – overwhelmingly publish in English peer-reviewed journals. <!--- The fact that PhDs publish papers during their PhD has consequences for how we will theorize on (gender differences in) collaborations. ---> But contrary to, for instance, the U.S., PhDs often do not shape their own topic, but apply to funded projects that are already carved out, oftentimes with an initial idea for what the final papers would need to look like. And the scientific norm is that PhDs and Postdocs publish with their advisors as co-authors, with the PhD or Postdoc, who is doing the majority of work, becoming the first author and the promoter or Principle Investigator of the project the last author.[^1] Thus for PhDs and Postdocs the choice set of possible co-authors are oftentimes limited to their more senior colleagues (formally) involved in their project, and for these groups in particular: first-authorships do not necessarily reflect intellectual leadership and co-authorship selection. <!---While PhD conferrals split approximately 50/50 between men and women doctoral students in the Netherlands nowadays, men's relative share increases with every step on the academic ladder. PhD (and PD) publishing practices and the gender composition of the departments alone may therefore impact how networks evolve and, for example, contribute to segregation along social identity dimensions like gender.---> <!--- The notion that PhDs (and PDs) take a special position within the co-authorship networks is underlined by the descriptives network statistics summarized in Table ... for egonets and in Table ... for the complete networks. For example, if we take the first author perspective the number of co-authors descreases if we exclude PhDs but if we take the last author perspective the number increases; thus yes,  --->

We therefore carefully need to nuance our conjectures on gender differences in co-authorship networks based on the career stage of scholars involved. The mechanisms of devaluation of personal scientific capital and the compensatory role of social scientific capital are most relevant for scholars who have agency in selecting collaborators. It is at the faculty ranks -- assistant professor and above -- that scholars accumulate and deploy scientific capital with meaningful discretion over whom they collaborate with. At this stage, personal scientific capital such as publication records and citation impact are legible signals of scholarly reputation, and social scientific capital such as network position reflect investments in collaborative relationships. Gender differences in how these resources convert into co-authorship ties are therefore most likely to emerge among faculty. While we include PhD students and postdocs in our analyses to capture the collaborative context in which faculty operate, our theoretical predictions regarding gendered returns to scientific capital apply primarily to faculty scholars. As such, we conjecture:

*Hypothesis 3: The gendered conversion of (a) personal and (b) social scientific capital into co-authorship ties is most pronounced among faculty, and attenuated or absent among PhD students and postdocs.*

[^1]: Sole authored papers are rare within these disciplines within the Netherlands, especially by PhD students or Postdocs.

<!-- RM: mijn hypothese zou zijn: vooral het mannelijke/upper rank accessed capital kan compenseren, maar het vrouwelijke/lower rank accessed capital minder, maar denk dat dat voor empirie te ver gaat? ---> 


<!--- to methods: While, our data at the tie-level is time-stamped (i.e. the publication data of the paper), we aggregated our network data to three approximately two-year time windows, because we collected scholar-level data (e.g. at which university they were employed) only at three time points (December 2022, March 2024, October 2025). We binarized the networks (i.e. yes/no tie) to reflect that co-authorships signal collaboration *relations* and are not short-term *events,* and because the co-authorship networks were already quite sparse and we observed only few multiple co-authorship occasions between the same scholars <!---percentage?)---> <!--- in the same time-window. This operationalization allows us to analyze the evolution of co-authorship networks via the Stochastic Actor Orientated Model as implemented in the R package RSiena which will describe in more detail in the 'Data and Methods' section. ----> 

<!--- i miss some intution on what these differences roles implyin the above paragraph --->


### Demographic characteristics

Naturally, decisions to make, maintain or break co-authorship ties are not only based on social scientific capitial indicators. Other mechanisms are at play at well and to isolate the impact of social scientific capital these need to be taken into account.

...

Social networks are oftentimes segregated along key social identity dimensions like gender, ethnic heritage, age and educational background. Social segregation is observed in core networks of strong ties as well as in the extended networks of acquaintances, it is observed in offline as well as online networks and both in informal networks of friendships as in formal networks of colleagues (?). <!---exceptions, negative networks, twitter networks?---> In part this is because people with similar demographic characteristics have more opportunities to meet each other due to shared 'foci', institutional and residential segregation spill-over into social segregation. Naturally, the most important foci scholars share are the department and discipline they work in. The Dutch sociology and political science departments differ to some extent in their composition (see table ...) possible thereby contributing to social segregation in the complete co-authorship network. While the gender composition within the disciplines of sociology and political science is fairly equally distributed, especially at the PhD-level (see table ...), within these disciplines there may still be differences in specific research topics scholars focus on, aligning with identity dimensions like gender and migration background, causing differences in between and within group meeting opportunities.

Another important reason for social segregation within networks is choice homophily, the preferences for people to interact with others with whom they share social characteristics. Similarity would facilitate trust, make the behavior of others more predictable and this would ease communication and collaboration. Unfortunately, our data lacks explicit measures of preferences for within group ties (or ingroup bias), but given the importance of choice homophily, we expect to observe that *scholars are more like to create and maintain ties with similar others (along gender and migration background and career age), even if we take into account differences in meeting opportunities (i.e. shared university and discipline, shared research topic; hypothesis 4a).*

<!-- but what if they select into these things nonrandomly? Dna lopen oorzaken gevolg door elkaar. Dus mediatie? EERST same gender, en gaat dat weg door die andere same dingen ---> 

Ingroup biases, and by extension choice homophily effects, may differ across social groups, with higher status groups commonly expressing stronger ingroup preferences. Moreover, members of lower status groups may also have stronger instrumental motives to create and maintain ties with high status outgroup members. <!---extend---> <!---queen bee effect?--->. Underlining this idea, in our data we also observe that the co-author networks of men exert a higher degree of gender homogeneity than the networks of women, as indicated by the stronger negative Krackhard and Stern's E-I index [@krackhardt1988] capturing the relative prevalence of between gender and within gender ties (see table ...). Naturally these descriptive statistics are not yet controlled for differences in opportunities or endogenous networks effects that could potentially exacerbate segregation patterns, nevertheless, *we expect to observe stronger choice homophily effects for men than for women and for native Dutch scholars as compared to scholars with an ethnic minority background (Hypothesis 4b).*

A final nuance of hypothesis 4 concerns the special positon of PhDs and PDs. Because, especially PhDs and PDs will have less agency to act upon their collaboration preferences, *we expect that choice homophily effects will be less pronounced among PhD students and Postdocs and hence in our network based on the first-author perspective (Hypothesis 4c).*

### Structural network effects

...

Structural network effects are likely to further exacerbate any initial inequalities in the network and without controlling for these effects the theorized mechanisms underlying (gender differences in) network dynamics may be overestimated.

...

## Data and methods

### Data

<!--- The data used in this contribution grew out of relatively small-scale hands-on network data collection assignments for students following the Research Master's course in Social Networks of our faculty. Among other things, in this course we discussed the unique characteristics of web-scraped publicly available social network data and how collecting this data would comply with our own ethical standards, the Ethics Code for Research in the Social and Behavioural Sciences, as well as the corresponding faculty guidelines of our university. After the present authors decided to 'professionalize' and streamline the datacollection process and to use the data for scientific purposes, we asked the Ethics Committee Social Sciences (ECSS) of our university for further advice, because the standard procedures to assess wither our research required an independent ethics assessment by the ECSS were not well suited for our type of data. Their conclusion was that we did not have to submit our project for review to the ECSS (Ethics reference number: 25U.01.4853; see also at our replication website).--->

<!--- This study contributes a database of scholars = XXXX and their publications = XXXX that is a near-population of staff employed in Sociology and Political Science departments at Dutch research universities between 2022 and 2025. --->

<!--# add acknowledgment to Anuschka Peelen and Niels Vullings for collecting anchor data --->

We manually collected staff lists from public sociology and political science departmental webpages of Dutch research universities at three time points (19 December 2022, 19 April 2024, and 12 October 2025). This information included staff members' names, discipline, university affiliation(s), and job title. All non-academic staff (e.g. support staff) and full-time lectures were removed. This constituted our scholar anchor database (N = ...). We linked these scholars to their publication histories via OpenAlex [@ref] up to February 2026. OpenAlex contains scholarly metadata, is open source and is increasingly used in bibliometric research [@priem2022]. We were able to link our authors to ... unique papers <!--# niet alleen papers! -->

All code used to construct our dataset can be found on our replication website. Both the complete dataset and the anonymised dataset (with identifiers of individual authors and papers removed) have been deposited at the Dutch Data Station Social Sciences and Humanities [@ref], with restricted and full open access respectively.

The data and data collection pipeline builds on the small-scale hands-on network data collection assignments for students who followed the Research Master's course in Social Networks of our faculty. After the present authors decided to streamline and scale-up the data collection process and to use the data for scientific purposes, we consulted the Ethics Committee Social Sciences (ECSS) of our university, because the standard decision tree of ECSS to assess wither our research required an independent ethics assessment was not well suited for our type of data (i.e. automatically and manually webscraped, publicly available social network data). The conclusion of the ECSS was that we did not have to submit our project for review to the ECSS (Ethics reference number: 25U.01.4853; see also at our replication website)

### Variables

#### Network Dependent Variables

*Co-authorship ties* were retrieved from the publication histories of our scholars as recorded on OpenAlex. To link scholars to OpenAlex, we first queried OpenAlex for the university identifiers our scholars worked at. Then, we queried OpenAlex for scholars full name, filtered by their OpenAlex institution identifier. In this way we retrieved for each scholar one or more OpenAlex author IDs. Some scholars have more than one profile (XX% of our scholars) due to changing names or institutional affiliations across publications, or due to false positives. To minimize false positives, we manually went through all authors with multiple IDs and assessed the name similarity; queried name versus name of OpenAlex profile page. We were not able to retrieve an OpenAlex ID for all scholars. To minimize false negatives we checked whether scholars without an OpenAlex author ID already published (via the departmental websites, personal websites and Google Scholar). If so, we searched for the output in OpenAlex and retrieved, if present, the author ID in this way. For ... scholars we did not find an author ID, the vast majority of which PhD students who have not yet published (...%). Using the OpenAlex author IDs, we webscraped for each linked scholar their complete publication history. The associated publication metadata consists of information like OpenAlex publication identifier, publication year, type of publication (e.g. book or journal paper) and, most importantly for our purposes, with whom the publication was written.

With this data at hand, we determined how many times any two scholars in our sample coauthored papers within a predetermined time-window. This resulted for each dyad in an undirected weighted collaboration tie for that time-window, which were stored in a series of adjacency matrices. We also took a first-author and last-author perspective and for each author assessed whether he or she was the first, or last author on respective co-authored papers. While, our data at the paper-level is in principle time-stamped (i.e. the publication data of the paper), we aggregated our network data to three waves with an approximate two-year time window; wave 1: 20 December 2020 until 19 December 2022; wave 2: 20 December 2022 until 19 March 2024; Wave 3: 20 March 2024 until 1 February 2026. The main reason for this aggregation step was because we collected scholar-level data (e.g. at which university they were employed) only at three time points. The time period between the midpoints of our waves had an approximately similar length of ... days. In a last step, we binarized the networks (i.e. yes/no tie) to reflect that co-authorships signal collaboration *relations* and are not short-term *events,* and because the co-authorship networks were already quite sparse – even after our aggregation step – and we observed only few multiple co-authorship occasions between the same scholars <!---percentage?)---> in the same time-window.

We thus have three different dependent variables; undirected co-authorship ties *(un_ties)*, first-author directed co-authorship ties (*first_ties*)and last-author co-authorship ties (*last_ties*), measured at three discrete time-points. This data and consequent operationalization allows us to analyze the evolution of co-authorship networks via the Stochastic Actor Orientated Model as implemented in the R package RSiena ([@RSiena]; see analytical strategy below). We will model each dependent variable separately.

#### Independent Variables

*Gender* was operationalized as an inferred gender indicator based on scholars’ first names. We used the `genderizeR` package to query the genderize.io database, which provides probabilistic gender assignments for first names based on large-scale social media data [@wais2016, see also genderize.io documentation]. We also matched first names to the Dutch public civic registry name database hosted by the Meertens Instituut (Nederlandse Voornamenbank), which contains all officially registered first names in the Netherlands and their distribution by sex over time [@meertensinstituut]. When the classification was inconsistent or missing we manually coded the gender of the scholar. <!---  Where available, this registry information was used to validate or refine the genderize.io-based assignments, especially for names with low counts or ambiguous probabilities in genderize.io. ---> <!--# Jos, klopt dit. meertens toch eerst dan genderizeR, ik lees dit niet in de code, -->

*Origin* was operationalized as an inferred country-of-origin indicator based on scholars’ surnames. We used the `DemografixeR` package to query the nationalize.io API, which provides probabilistic nationality assignments for last names based on large-scale web data [@brenninkmeijer2025, see also nationalize.io documentation]. We also collected information on country-of-origin via the Dutch Database of Surnames in the Netherlands (Nederlandse Familienamenbank), which reports the number of name bearers per surname and provides etymological notes on its origin and meaning [@centrumvoorfamiliegeschiedenis]. We combined the various signals to ISO 3166-1 alpha-2 country codes and manually filled in missing values (see our replication website for more details). Finally, we categorised country-of-origin into (1) Dutch; (2) Turkish, Surinamese, Moroccan, Dutch Antillean or (3) other. Scholars assigned to the Turkish, Surinamese, Moroccan and Dutch Antillean category are predominantly second generation migrants who followed most part of their educational career in the Netherlands. Scholars assigned to the 'other' category are mostly scholars who either joined Dutch academia as PhD student or later (cf. Tolsma...).

*Career age* was based on the publication year of the first <!--- [or second??] ---> paper of each scholar as: 2027 - year-of-first-publication.

*Position* indicates scholars’ academic rank within the Dutch university system. Starting from the free-text job titles collected from departmental staff pages, we mapped all ranks to a set of six categories: *PhD student*, *Postdoc*, *Researcher*, *Assistant professor*, *Associate professor*, and *Full professor* (including endowed, visiting and emerita).

*Discipline* indicates whether a scholar is employed at a sociology or political science department. Based on this informatin we also constructed the dyad-level variable *same-discipline* (based on possibly two university affiliations).

*University.* For each scholar we know at which of the eight university or universities he or she was employed; Radboud University (RU), Erasmus University Rotterdam (EUR), University of Amsterdam (UVA), Leiden University (LU), Vrije Universiteit Amsterdam (VU), Utrecht University (UU), Tilburg University (UVT), and University of Groningen (RUG). We also used this information to construct the dyad-level variable *same-university* (based on possibly two university affiliations). Finally, based on the primary affiliation of the scholars we constructed the *geographic-distance* dyad-levelvariable indicating the travel time in hours by public transport between the universities of the involved scholars as retrieved from 9292.nl the main public transport API for the Netherlands.

*Interdisciplinarity.* We measure the degree of research interdisciplinarity of each scholar based on the subfields scholars publish in. In OpenAlex each paper is assigned to multiple Domains, Fields, Sub-Fields and Topics (for more details see ...). Domain and Field are too broad categories to distinguish our scholars. OpenAlex distinguishes ... Topics, this we considered too fine-grained. We therefore decided to use the Sub-Field level to measure the degree of author's interdisciplinarity. Based on all harvested papers from all the authors in our sample with a publication year between 1990 and 2006, we constructed a cosine distance matrix $D$ between the different subfields $i$. This distance matrix was converted to a proximity matrix $w$ via a biweight kernel proximity function: $w_{ij} = 1 - (D_{ij}/max(D))^2$, with $i$ and $j$ indexing the different subfields. A score of 1 indicated maximum subfield similarity and 0 maximum dissimilarity. For each wave and author, we constructed a subfield profile using all author's publications in the two-year retrospective window, determining for each subfield the proportion of papers categorised as such, the subfield shares $p_i$. We then defined author interdisciplinarity (AI) as $AI = 1-  \Sigma_{ij}p_{i}*p_{j}*w_{ij}$ [@ref].

*Subfield similarity.* To assess authors' similarity in research subfields, a time-varying dyad-level variable, we followed a similar procedure. Based on the subfield profiles of the authors we once again constructed a cosine distance matrix, but now measuring the distance between authors. This distance matrix was converted to a proximity matrix. A score of 1 indicated maximum author similarity and 0 maximum dissimilarity.

*I10-index* is a time-varying variable indicating the number of articles of each author cited by at least 10 sources.

We included the variables gender, origin, career age, position, university, interdisciplinarity and i10-index at the ego (sending ties; covariate-ego) and alter (receiving ties; covariate-alter) level in our explanatory models to take into account possible individual-level differences in publication rates (and popularity as co-author) and to take into account that publication rates can vary across universities, disciplines, fields and career stages. At the dyad-level, same-discipline, same-university, and geographic-distance is included to account for collaboration opportunities; that physical proximity fosters collaboration. Same-gender, same-origin and similar career-age is included to assess choice homophily tendencies.

### RSiena

In RSiena the evolution of the network between two discretely observed time-points (or waves) is simulated via so-called ministeps. During a ministep one actor is allowed to make one tie-change; break or make one tie. The probability that a specific actor will be the next to have an opportunity to make a ministep is modelled via the rate-function. Which tie-change is most likely is modelled via the evaluation function. For the actor that is allowed to make a tie-change, the evaluation function evaluates the local network neighbourhood that would result from the tie-change under consideration. The evaluation function is constructed as a linear combination of effects (e.g. reciprocity, transitivity) and for each effect the corresponding parameter is estimated. That is, the simulation of the network evolution between time *t* and *t + 1* starts with the network at time *t* as given. The algorithm aims to optimize the user-defined rate and evaluation function in such a way that the simulated network resembles the network at time *t + 1* with respect to the effects included in evaluation function. When a parameter is positive this means that a tie change that increases the effect (e.g. the number of reciprocated ties increases in the local neighbourhood after the tie-change under consideration) is more likely than a tie-change that leaves the effect unaltered. For an easy introduction into RSiena and for a more thorough explanation of the simulation process and interpretation of the parameters see Tolsma and Hofstra 2024; chapter 7.

### Model specification

The rate-function models the speed by which the co-authorship ties change. Given that the (out)degree distribution is very skewed (see Figure ...) and our network has a clear core-periphery structure (see Figure ...), we let the rate function depend on the outdegrees. We hereby give actors with a higher outdegree more opportunity for changing her co-authorship ties.

Our main focus is, however, on the evaluation function that determines the probabilities of tie-changes. We included the baseline structural effects *density* and *reciprocity* (directed networks only). The *transitive triplets effect* is included to represent transitivity (a co-author of a co-author becomes my co-author). We also included the *three-cycles* *effect* (directed networks only) because a positive transitive triplets effect together with a negative three-cycles effect may be interpreted as a tendency toward local hierarchy, which we expect given different roles related to authorship position. We also take into account the dispersion of degrees. In the directed networks via the *in-degree popularity squared*, and *out-degree activity squared* effects. For the directed network via the

For the directed network we assume that one actor takes the initiative and proposes a new collaboration or stops an existing collaboration. If the scholar proposes a new collaboration, we assume the other scholar has to conform, otherwise the tie is not created. For stopping an existing collaboration no confirmation is required. Technically, we set the modelType option in the simulation algorithm to 3.

We start with a model including all structural effects described above and the covariate-ego and covariate-alter effects that proved relevant, and the effects by which we aim to capture collaboration opportunities. From this model, we will learn to what extent we favor women or men as co-author. We then include the effects by which we aim to assess choice homophily. In the final model, we will test our hypotheses regarding the differential impact of (social) science capital indicators (i.e. i10-index, rank, indegree popularity) across men and women by including the interactions of these indicators by the gender-alter effect.

## Results

### Descriptive statistics

#### ego-level / scholars

#### egonets

To some extent, we observe similar patterns in our data. For example, in the period 2022 and 2024, the number of distinct Dutch employed sociologists or political scientists women worked with is smaller than for men (on average 1 versus 1.3). The networks of male social scientists are also more tightly knit, as indicated by the higher clustering coefficients (Table ...). However, in contrast to previous work, we observe that among Dutch sociologists and political scientists, women are more likely than men to collaborate with scholars from universities other than one's own, as indicated by the less negative Krackhard and Stern's E-I index [@krackhardt1988] capturing the relative prevalence of between university and within university ties (see table ...). and are, thus, less locally orientated. Such descriptive statistics – of prior work and our own – however, elude the complex interdependent network dynamics from which they are the result. <!---en dus? nl anders, onze disciplines anders. mis punchline. en daarom moeten we kijken naar dynamics-->

<!---describe some--->

.

#### complete networks

some graphics as well.

### RSiena results

## Conclusion/discussion

genarative AI, future of papers/collaboration. more and more papers. instead of working with real people, with AI agentic agents? is this chance or threat to gender inequality in academica?? reduces collaboration. see paper nature 2026 Hao, q, nature 649. PD roles are shrinking the fastest?

ai might be used as compensating strategy of one lacks scientific capital in real-life collaboration networks.

Dong, 2026 proved that genai improves writing skills under specific conditions.

## References
