---
title: "Gender inequality in co-authorship networks in Dutch academia"


code-repo: "Access the code, data, and analysis at <https://github.com/jossl95/co-pub_networks>"
correspondence-prefix: "Correspondence concerning this article should be addressed to"

author: 
  - name: "Bas Hofstra"
    orcid: 0000-0002-9052-956X
    affiliations:
      - ref: RU
  - name: "Jos Slabbekoorn"
    orcid: 0000-0001-8419-5703
    #email: jos.slabbekoorn@ru.nl
    affiliations: 
      - id: RU
        name: Radboud University Nijmegen
        department: Sociology
        country: The Netherlands
  - name: "Roza Meuleman"
    orcid: 0000-0002-4486-253X
    affiliations:
      - ref: RU
  - name: "Jochem Tolsma"
    orcid: 0000-0002-4411-6932
    email: jochem.tolsma@ru.nl
    affiliations:
      - ref: RU
      - id: RUG
        name: University of Groningen
        department: Sociology
        country: The Netherlands
    attributes:
      corresponding: true

date: today

excluded:
  - paper1/_archive

keywords: 
   - Gender inequality in academia
   - Co-Authorship Networks
   - Scientific capital
   - Social network analysis
bibliography: references.bib
---

## Introduction

<!--# worsteling: scientific capital is nu ook gedefinieerd op het individuele niveau (mijn i-index, mijn positie) en niet enkel op het (egocentric) co-authorship network niveau. Dat is eigenlijk vreemd, want we willen het social network perspective centraal stellen. scientific capital centraal stellen, maar wmb eigenlijk vooral scientific capital embedded in networks. Oplossing, social scientific capital -->
<!---# of scientific social capital ?---?
<!---start met het overkoepelende probleem dat centraal staat: (gender) inequality in academia. de Y--->

Gender disparities in academic careers are persistent and well-documented [e.g., @barrios2013; @bol2023; @greska2023; @kim2022; @lutter2016]. Women earn lower salaries, secure fewer grants, receive less recognition for innovative work, and experience shorter, less prolific careers compared to men [@hofstra2020; @kim2024; @mulders2024; @tolsma2025]. They are also more likely to work on research topics and innovations that yield lower career returns [@hofstra2020; @kim2024]. Such enequalities in academia are not limited to gender. Minoritized scholars - by national origin, ethnic background, or skin color - face barriers as well, including those that slow career progression to senior academic positions [@hofstra2020; @kozlowski2022; @whittington2018]. <!--- kan weg: First-generation scholars, too, often struggle to navigate the academic environment, slowing their advancement within academia. --->

<!--al veel bekend--->

The mechanisms causing these inequalities are increasingly understood. They range from biases in selection and promotion committees, overt discrimination and hidden micro aggressions leading to chilly lab or office climates for women and minoritized persons, to discriminatory institutional policies (e.g. regarding parental leave) and differences in work preferences (e.g. differences in preferred discipline, or team science prevalence). In some areas there has been some progress towards equity. In the Netherlands, the current empirical site, for example, targeted policies have reduced early-career disparities. Women and ethnic minority scholars are now as likely as their peers to start a PhD and women increasingly transition to faculty positions. As such, early-career grant gaps have narrowed, and more women are reaching professorial ranks. Yet, this does not mean that gender equality in (Dutch) academia is only a matter of time. Pay gaps widen quickly after the PhD-stage and women are still more likely than men to leave academia earlier in their career. This 'leaky pipeline' not only widens pay gaps but also perpetuates the persistent underrepresentation of women at the senior positions in academia. Gender inequality in Dutch academia, it seems, becomes most pronounced after the early career stages. <!---hiermee sorteer ik voor op BH's PhD interacties Bas: nice--->

<!--introductie onze angle via trechtermodel--->

In this study, we argue that a critical yet overlooked factor in academic inequality -- and one that becomes especially relevant after early career stages -- are social networks. In labor market and health inequality research, social networks are often seen as both a potential buffer against and a catalyst for inequality. Disadvantaged groups may use networks to compensate for resource deficits, but more commonly, networks exacerbate inequality by distributing power to the privileged, reproducing existing hierarchies. Such processes are likely in academia as well, as knowledge production is inherently social. Journal papers are reviewed by (unanimous) peers. Departmental colleagues, disciplinary conferences, and varieties of academic committees are all central to academic norms and practices [@burt1998; @stark2020; @bourdieu1988]. Additionally, previous work demonstrated that access to prestigious academic positions depend on one’s mentors [@hofstra2022] <!---but see AM that supervisorteam do not have impact, BH: better direct measures in my paper--->; that dissertation committees exhibit gender-homophilous tendencies in awarding cum laude graduate degrees [@bol2023]; and that the size and composition of co-authorship teams dictate whether papers are disruptive or consolidating in their findings [@wu2019]. Differences in academic socialization and the networks that one moves through constitute a central pathway for the genesis en reproduction of inequalities.

<!---arguments why we study co-authorship netwerks--->
Co-authors are among the key social relationships in academics' careers: peer-reviewed papers with co-authors are the essential form to contemporary academic knowledge production [@ref] and journal papers are still a main aspect of academic evaluation. Working together on papers dynamically shapes productivity and visibility [@abbasi2011; @ductor2015; @li2022; @moody2004; @newman2001; @wallace2012]. The average number of co-authors on papers is increasing [@refDAHSUNWNAG?] as team science is increasingly common. Being less able to connect to and sustain (past) co-authors harboring 'scientific capital' leaves long-lasting negative effects on academic careers. It implies less access to co-authors with like team science skills, complementary theoretical or methodological knowledge, who have access to funds, data or research assistants. Differences in these co-author networks – whether in size, structure, or composition – may not only contribute to further inequality, they are by themselves a potential source of inequality in academia. In this contribution, we therefore set out to answer the following central question: <!--- (1) *To what extent do co-authorship differ by gender?* and (2) ---> *How do co-authorship networks evolve over time, and how do these dynamics differ by gender?* <!--- Our first research question takes a *static* perspective, while the second deals with the *evolution* of co-authorship networks formed by a population of scholars in our study. This is intentional, as answering both questions in tandem, ---> By answering our question we aim to deepen our understanding of the degree of, and the mechanisms driving gender inequality in academia. We do so in three ways.

<!---site of study--->

Our empirical setting is the Netherlands, where we analyze the co-authorship networks of all sociologists and political scientists employed at Dutch universities between 2022 and 2025 (N=1.175). We selected these disciplines for various reasons: <!--- first, much of the literature on academic inequality focuses on STEM fields, leaving social sciences understudied; <!--- BH: sociology is perhaps the most studied field in history, by sociologists, so I'll remove this one. --->  first, both disciplines have near gender parity at the PhD level, allowing us to compare network dynamics across genders; second, their research outputs are predominantly multi-authored, international journal articles – and not monographs, patents, or publications in Dutch –, enabling reliable network construction, and third, we assume that co-authorship networks in these fields are largely domestic, making our data more comprehensive (i.e. capturing the large majority of co-authorships) than would we have selected more internationally oriented disciplines like anthropology or physics. Moreover, a focus on a limited set of disciplines makes it manageable to model the evolution of the co-authorship networks while allowing for (gender differences in) cross-disciplinary and cross-university collaborations. In sum, our empirical site is ideal for a in-depth study of complex network dynamics.

<!---naar type verklaringen--->

So what are these network dynamics? To model our network's evolution, we draw on social network theory. Obvious starting points involve choice homophily, or the preference to form relations with people who are similar to us [@MCPHERSONS2001], as ths is quite ubiquitous in social life. We therefore study how socio-demographic similarity between scholars on gender and migration background drive network dynamics. Next to such preferences, we also aim to take into account possible differences in collaboration *opportunities*. For example, we will study similarity related to the university scholars work at, their main discipline, and their specific research topics. These factors may impact preferences for collaboration but certainly also shape opportunity structures. Yet to properly consider these mechanisms, we also account for *endogenous structural network effects* that commonly drive network evolution so as to accurately isolate homophily from dynamics related to reciprocity, triadic closure, preferential attachment and brokerage [@barabasi1999; @bojanowski2020; @ebadi2015; @gondal2011; @gondal2018] and have have found to be relevant in collaboration networks as well [@gao2022; @kwiek2021; @whittington2024; @hancean2014]. Yet what distinguishes our study is its primary focus: how characteristics such as career stage, productivity, and the size, structure, and composition of a scholar's past co-authorship network shape their attractiveness as a future collaborator, and whether these scientific capital indicators are valued differently for men and women. We develop two main hypothesis strands around this question. The first draws on work showing that women may derive greater returns from scientific social and personal capital precisely because they must rely on it more heavily to achieve comparable outcomes to men. The second concerns the devaluation of women's contributions, yielding fewer returns per unit of equivalent scientific personal or social capital. Crucially, we examine each these network mechanisms in combination, moving beyond prior work that typically treats them in isolation. This allows us to study the reproduction of gender inequality in scientific co-authorship networks.

<!--- spoiler, komt later wel Our general hypotheses -- for which we will provide more argumentation in the next section -- are: (1) Women scholars possess less scientific capital than men, both personally as well as embedded in the co-authorship network; and (2) that women’s scientific capital is less likely to lead to co-authorships than men's, contributing to persistent gender inequality in academic networks. --->

<!---contributions--->

So given our empirical site and focus, our study contributes to the literature on inequality in academia in several ways. First, we contribute the concept of scientific social capital which scholars can either possess themselves *and* which is also sourced from their collaboration networks. We contribute a social network perspective, by treating co-authorship networks as both a potential site and a driver of gender inequality. We  compare differences in scientific capital by gender but also move beyond descriptive analyses by investigating how the complete network of co-authorships develops over time. We do so by drawing from comprehensive data on the near-population of sociology and political science scholars in Dutch universities (including PhD-students) between (2022 and 2025) and their co-authorship histories. We thus reduced the influence of survivor and publication bias that commonly distorts conventional bibliometric network studies [@simko2015] with a focus on highly productive (senior) scholars or the output published within specific selected journals [@hancean2014; @ossenblok2014]. When explaining network dynamics, we recognize the importance of structural network effects, and mechanisms related to preferences and opportunity structures. But importantly, we assess the extent to which scientific capital indicators shape networks differently for men and women. We model the evolution of the complete co-authorship network with the Stoachastic Actor Orientated Model as implemented in RSiena. With this, we are among the first to explicitly model path dependency and endogenous network processes using longitudinal network models, shifting the focus from mere descriptive differences to the network processes through which these inequalities emerge and are reproduced. Finally, our data set is made publicly available for the scientific community on the replication website that accompanies this contribution (WEBLINK).

<!--- I am unsure whether this entire last paragraph i necessary. Ik vond het goed lopen tot "type verklaringen" iets ge-edit, past nu beter--->

## Theory

<!---onze methode introduceren. hiervoor nodig om def van netwerk te geven, dit wordt eerste alinea theorie--->

### Authorship in the Dutch social science context

How to theoretically define and consecutively operationalize a co-author-relation is not self-evident. Scholars may work together on a paper, but contribute in different ways and occupy different team roles. Similarly, when putting together the team of co-authors, not all scholars will have had the same agency, not in proposing potential collaborators, nor in refusing received 'invitations'. To construct our co-authorship networks we rely on the journal papers of our scholars in our sample (....unique papers). Based on this, we constructed two *directed* co-authorship networks: one in which we take a 'first author perspective' in which the first author sends the co-author ties to all other co-authors, and one in which we take a 'last author perspective and take the last author as the one sending ties to all others co-authors. A first-author perspective may signal intellectual leadership and active co-author selection, whereas last authorship may reflect seniority, supervision, and convening collaborators. These roles carry different kinds of agency in shaping who works with whom, and they may even be distributed unequally across gender. Studying ties from both perspectives enables us to assess whether network dynamics and gender disparities manifest differently depending on the type of collaborative agency at stake. This is even further nuanced when we consider the special network position of PhDs and postdocs.

<!--- to methods: While, our data at the tie-level is time-stamped (i.e. the publication data of the paper), we aggregated our network data to three approximately two-year time windows, because we collected scholar-level data (e.g. at which university they were employed) only at three time points (December 2022, March 2024, October 2025). We binarized the networks (i.e. yes/no tie) to reflect that co-authorships signal collaboration *relations* and are not short-term *events,* and because the co-authorship networks were already quite sparse and we observed only few multiple co-authorship occasions between the same scholars <!---percentage?)---> <!--- in the same time-window. This operationalization allows us to analyze the evolution of co-authorship networks via the Stochastic Actor Orientated Model as implemented in the R package RSiena which will describe in more detail in the 'Data and Methods' section. ----> 

<!--- i miss some intution on what these differences roles implyin the above paragraph --->

### The special (network) position of PhDs and Postdocs

The research sites in which we answer our questions are the disciplines of sociology and political sciences across the research universities in the Netherlands, if they have any such clearly delineated departments. In these disciplines, PhD students are often a cornerstone of a department's publishing activity, where dissertations are almost without exception a collection of (near) published papers, particularly so in the years we consider. Sociologists and political scientists in the Netherlands – PhDs and faculty alike – overwhelmingly publish in English peer-reviewed journals. <!--- The fact that PhDs publish papers during their PhD has consequences for how we will theorize on (gender differences in) collaborations. ---> But contrary to, for instance, the U.S., PhDs often do not shape their own topic, but apply to funded projects that are already carved out, oftentimes with an initial idea for what the final papers would need to look like. And the scientific norm is that PhDs and Postdocs publish with their advisors as co-authors, with the PhD or Postdoc, who is doing the majority of work, becoming the first author and the promoter or Principle Investigator of the project the last author.[^1] Thus for PhDs and Postdocs the choice set of possible co-authors are oftentimes limited to their more senior colleagues (formally) involved in their project, and for these groups in particular: first-authorships do not necessarily reflect intellectual leadership and co-authorship selection. <!---While PhD conferrals split approximately 50/50 between men and women doctoral students in the Netherlands nowadays, men's relative share increases with every step on the academic ladder. PhD (and PD) publishing practices and the gender composition of the departments alone may therefore impact how networks evolve and, for example, contribute to segregation along social identity dimensions like gender.---> <!--- The notion that PhDs (and PDs) take a special position within the co-authorship networks is underlined by the descriptives network statistics summarized in Table ... for egonets and in Table ... for the complete networks. For example, if we take the first author perspective the number of co-authors descreases if we exclude PhDs but if we take the last author perspective the number increases; thus yes,  ---> We therefore carefully need to nuance our conjectures on gender differences in co-authorship networks and developments therein based on the position of scholars involved.

[^1]: Sole authored papers are rare within these disciplines within the Netherlands, especially by PhD students or Postdocs.

### Scientific personal and social capital

We distinguish between scientific *personal* and *social* capital. Scientific personal capital refers to the individual-level features that scholars accumulate through their own output: productivity, citation impact, and academic rank. These features signal reputation and competence to potential collaborators and may shape how attractive a scholar is as a future co-author. Scientific social capital, by contrast, is relational: these are features that encompass both structural characteristics of collaboration networks such as size and density as well as the resources embedded within it, such as the prestige of co-authors or the presence of crossdiscipline ties. These social resources matter because scholars are embedded in networks that open or close pathways for future collaboration opportunities. Someone well positioned in a prestigious network signals access to knowledge and expertise such that prospective collaborators seek them out. Together, these two dimensions capture the bundle of assets that scholars bring to future collaborations. As such, we conjecture:

*Hypothesis 1: Scholars prefer to collaborate with counterparts possessing scientific (a) personal and (b) social capital.*

Prior work work showed how scientific personal capital is unequally distributed by gender, where women obtain fewer grants, fewer citations, and populate lower ranks than men academics [BERTERE REFS HIER: Lerman et al. 2022; @hofstra2020; @mulders2024; @tolsma2025]. Prior work showed that women publish less than men and that they populate fewer senior authorship positions [@barrios2013; @tolsma2025], even if they contribute equally. Women are also less likely than men to occupy powerful positions in (co-authorship) networks [@gao2022; @whittington2018; @whittington2024], with women’s scientific collaborations more often being local and domestic and not internationally orientated [@kwiek2021]. But rather than studying *access to* these assets, we uniquely study the returns to these assets as they may differ systematically by gender. Equivalent scientific capital translates into different collaborative opportunities for men and women, though the ways in which they do so are not straightforward.


### Structural devalution or a neccessary compensating strategy?
Yet the direction of this gender asymmetry is theoretically ambiguous, and we distinguish hypotheses that move beyond contrasting ones. A substantial literature documents the devaluation of women's contributions in science (e.g., for career progression, salary) [@hofstra2020; @kim2024]: the Matilda Effect (ROSSITER 1993). If evaluators discount the productivity, impact, or network positions of women scholars, then similar scientific personal and social capital translates into fewer collaborative returns for women. Such devaluation of scientific capital may source from implicit bias, where the image of a competent, achieving scientists is predominantly male, and women's contributions are attributed to luck rather than ability. This structural devaluation logic predicts a gender penalty: although women bring the same assets to the table, these assets are worth less in the market for collaboration.

On the other hand, women in academia face well-documented barriers: implicit bias, exclusion from informal networks, and so forth. Where such barriers operate, scientific capital may function as a compensatory resource: women must signal these capitals more clearly, simply to be seen as equally attractive collaborators. Under this logic, equivalent scientific personal and social capital yields stronger returns for women, not because their capital is more valued, but because they have had to rely on it more heavily to overcome structural disadvantages in their careers.

But importantly, the devaluation or compensation logic need not operate uniformly across both dimensions of scientific capital. Scientific personal capital and social capital are evaluated through different mechanisms, and gender bias may operate more accutely in one versus the other. Scientific personal capital (productivity, citation impact, career stage) may often be individually attributed. This individual attribution renders it vulnerable to gendered devaluation. A substantial literature shows that evaluators systematically discount the personal contributions of women scholars when assessing the same outputs. These mechanisms relate to implicit biases that operates most  when judgments concern individual merit and competence, the domains where gender stereotypes are  activated. <!--- zit ewat redundantie in--->

Scientific social capital, by contrast, is relational and therefore evaluated differently. Network position, the prestige of one's co-authors, and cross-disciplinary ties are not so straightforwardly attributed to individual merit alone. A prestigious co-author is a prestigious co-author regardless of the gender of the scholar they collaborate with, and a large, dense network signals access to resources that prospective collaborators can observe and potentially benefit from. To the extent that scientific social capital functions as a signal of collaborative value based on *others*, it may be less susceptible to the kind of individual-level discount applied to scientific personal capital. Network-based status may in some cases operate as a resource that insulates women from competence-based bias. Women academics can therefore strategically lever their networks so as to overcome devaluation of their personal capital. 

As such, beyond the question of whether capital yields higher or lower returns for women, we consider a more nuanced possibility: that devaluation is not uniform but selective, operating through the mechanisms by which different types of capital are valued differently rather than through an overall discount on women scholars as collaborators. As such, we conjecture: 

*Hypothesis 2: Gender devaluation in collaboration is selective — (a) the scientific personal capital of women scholars is less likely to lead to co-authorships,  whereas (b) their scientific social capital is more likely to lead to co-authorships.*

We adjudicate between these predictions empirically by estimating gender-specific effects of scientific personal and social capital on tie formation in our stochastic actor-based models, allowing us to study not only how capital yields differential returns by gender, but whether those returns vary across career stage as well.  



### Demographic characteristics

Naturally, decisions to make, maintain or break co-authorship ties are not only based on social scientific capitial indicators. Other mechanisms are at play at well and to isolate the impact of social scientific capital these need to be taken into account.

...

Social networks are oftentimes segregated along key social identity dimensions like gender, ethnic heritage, age and educational background. Social segregation is observed in core networks of strong ties as well as in the extended networks of acquaintances, it is observed in offline as well as online networks and both in informal networks of friendships as in formal networks of colleagues (?). <!---exceptions, negative networks, twitter networks?---> In part this is because people with similar demographic characteristics have more opportunities to meet each other due to shared 'foci', institutional and residential segregation spill-over into social segregation. Naturally, the most important foci scholars share are the department and discipline they work in. The Dutch sociology and political science departments differ to some extent in their composition (see table ...) possible thereby contributing to social segregation in the complete co-authorship network. While the gender composition within the disciplines of sociology and political science is fairly equally distributed, especially at the PhD-level (see table ...), within these disciplines there may still be differences in specific research topics scholars focus on, aligning with identity dimensions like gender and migration background, causing differences in between and within group meeting opportunities.

Another important reason for social segregation within networks is choice homophily, the preferences for people to interact with others with whom they share social characteristics. Similarity would facilitate trust, make the behavior of others more predictable and this would ease communication and collaboration. Unfortunately, our data lacks explicit measures of preferences for within group ties (or ingroup bias), but given the importance of choice homophily, we expect to observe that *scholars are more like to create and maintain ties with similar others (along gender and migration background and career age), even if we take into account differences in meeting opportunities (i.e. shared university and discipline, shared research topic; hypothesis 4a).*

<!-- but what if they select into these things nonrandomly? Dna lopen oorzaken gevolg door elkaar. Dus mediatie? EERST same gender, en gaat dat weg door die andere same dingen ---> 

Ingroup biases, and by extension choice homophily effects, may differ across social groups, with higher status groups commonly expressing stronger ingroup preferences. Moreover, members of lower status groups may also have stronger instrumental motives to create and maintain ties with high status outgroup members. <!---extend---> <!---queen bee effect?--->. Underlining this idea, in our data we also observe that the co-author networks of men exert a higher degree of gender homogeneity than the networks of women, as indicated by the stronger negative Krackhard and Stern's E-I index [@krackhardt1988] capturing the relative prevalence of between gender and within gender ties (see table ...). Naturally these descriptive statistics are not yet controlled for differences in opportunities or endogenous networks effects that could potentially exacerbate segregation patterns, nevertheless, *we expect to observe stronger choice homophily effects for men than for women and for native Dutch scholars as compared to scholars with an ethnic minority background (Hypothesis 4b).*

A final nuance of hypothesis 4 concerns the special positon of PhDs and PDs. Because, especially PhDs and PDs will have less agency to act upon their collaboration preferences, *we expect that choice homophily effects will be less pronounced among PhD students and Postdocs and hence in our network based on the first-author perspective (Hypothesis 4c).*

### Structural network effects

...

Structural network effects are likely to further exacerbate any initial inequalities in the network and without controlling for these effects the theorized mechanisms underlying (gender differences in) network dynamics may be overestimated.

...

## Data and methods

### Data

<!--- The data used in this contribution grew out of relatively small-scale hands-on network data collection assignments for students following the Research Master's course in Social Networks of our faculty. Among other things, in this course we discussed the unique characteristics of web-scraped publicly available social network data and how collecting this data would comply with our own ethical standards, the Ethics Code for Research in the Social and Behavioural Sciences, as well as the corresponding faculty guidelines of our university. After the present authors decided to 'professionalize' and streamline the datacollection process and to use the data for scientific purposes, we asked the Ethics Committee Social Sciences (ECSS) of our university for further advice, because the standard procedures to assess wither our research required an independent ethics assessment by the ECSS were not well suited for our type of data. Their conclusion was that we did not have to submit our project for review to the ECSS (Ethics reference number: 25U.01.4853; see also at our replication website).--->

<!--- This study contributes a database of scholars = XXXX and their publications = XXXX that is a near-population of staff employed in Sociology and Political Science departments at Dutch research universities between 2022 and 2025. --->

<!--# add acknowledgment to Anuschka Peelen and Niels Vullings for collecting anchor data --->

We manually collected staff lists from public sociology and political science departmental webpages of Dutch research universities at three time points (19 December 2022, 19 April 2024, and 12 October 2025). This information included staff members' names, discipline, university affiliation(s), and job title. All non-academic staff (e.g. support staff) and full-time lectures were removed. This constituted our scholar anchor database (N = ...). We linked these scholars to their publication histories via OpenAlex [@ref] up to February 2026. OpenAlex contains scholarly metadata, is open source and is increasingly used in bibliometric research [@priem2022]. We were able to link our authors to ... unique papers <!--# niet alleen papers! -->

All code used to construct our dataset can be found on our replication website. Both the complete dataset and the anonymised dataset (with identifiers of individual authors and papers removed) have been deposited at the Dutch Data Station Social Sciences and Humanities [@ref], with restricted and full open access respectively.

The data and data collection pipeline builds on the small-scale hands-on network data collection assignments for students who followed the Research Master's course in Social Networks of our faculty. After the present authors decided to streamline and scale-up the data collection process and to use the data for scientific purposes, we consulted the Ethics Committee Social Sciences (ECSS) of our university, because the standard decision tree of ECSS to assess wither our research required an independent ethics assessment was not well suited for our type of data (i.e. automatically and manually webscraped, publicly available social network data). The conclusion of the ECSS was that we did not have to submit our project for review to the ECSS (Ethics reference number: 25U.01.4853; see also at our replication website)

### Variables

#### Network Dependent Variables

*Co-authorship ties* were retrieved from the publication histories of our scholars as recorded on OpenAlex. To link scholars to OpenAlex, we first queried OpenAlex for the university identifiers our scholars worked at. Then, we queried OpenAlex for scholars full name, filtered by their OpenAlex institution identifier. In this way we retrieved for each scholar one or more OpenAlex author IDs. Some scholars have more than one profile (XX% of our scholars) due to changing names or institutional affiliations across publications, or due to false positives. To minimize false positives, we manually went through all authors with multiple IDs and assessed the name similarity; queried name versus name of OpenAlex profile page. We were not able to retrieve an OpenAlex ID for all scholars. To minimize false negatives we checked whether scholars without an OpenAlex author ID already published (via the departmental websites, personal websites and Google Scholar). If so, we searched for the output in OpenAlex and retrieved, if present, the author ID in this way. For ... scholars we did not find an author ID, the vast majority of which PhD students who have not yet published (...%). Using the OpenAlex author IDs, we webscraped for each linked scholar their complete publication history. The associated publication metadata consists of information like OpenAlex publication identifier, publication year, type of publication (e.g. book or journal paper) and, most importantly for our purposes, with whom the publication was written.

With this data at hand, we determined how many times any two scholars in our sample coauthored papers within a predetermined time-window. This resulted for each dyad in an undirected weighted collaboration tie for that time-window, which were stored in a series of adjacency matrices. We also took a first-author and last-author perspective and for each author assessed whether he or she was the first, or last author on respective co-authored papers. While, our data at the paper-level is in principle time-stamped (i.e. the publication data of the paper), we aggregated our network data to three waves with an approximate two-year time window; wave 1: 20 December 2020 until 19 December 2022; wave 2: 20 December 2022 until 19 March 2024; Wave 3: 20 March 2024 until 1 February 2026. The main reason for this aggregation step was because we collected scholar-level data (e.g. at which university they were employed) only at three time points. The time period between the midpoints of our waves had an approximately similar length of ... days. In a last step, we binarized the networks (i.e. yes/no tie) to reflect that co-authorships signal collaboration *relations* and are not short-term *events,* and because the co-authorship networks were already quite sparse – even after our aggregation step – and we observed only few multiple co-authorship occasions between the same scholars <!---percentage?)---> in the same time-window.

We thus have three different dependent variables; undirected co-authorship ties *(un_ties)*, first-author directed co-authorship ties (*first_ties*)and last-author co-authorship ties (*last_ties*), measured at three discrete time-points. This data and consequent operationalization allows us to analyze the evolution of co-authorship networks via the Stochastic Actor Orientated Model as implemented in the R package RSiena ([@RSiena]; see analytical strategy below). We will model each dependent variable separately.

#### Independent Variables

*Gender* was operationalized as an inferred gender indicator based on scholars’ first names. We used the `genderizeR` package to query the genderize.io database, which provides probabilistic gender assignments for first names based on large-scale social media data [@wais2016, see also genderize.io documentation]. We also matched first names to the Dutch public civic registry name database hosted by the Meertens Instituut (Nederlandse Voornamenbank), which contains all officially registered first names in the Netherlands and their distribution by sex over time [@meertensinstituut]. When the classification was inconsistent or missing we manually coded the gender of the scholar. <!---  Where available, this registry information was used to validate or refine the genderize.io-based assignments, especially for names with low counts or ambiguous probabilities in genderize.io. ---> <!--# Jos, klopt dit. meertens toch eerst dan genderizeR, ik lees dit niet in de code, -->

*Origin* was operationalized as an inferred country-of-origin indicator based on scholars’ surnames. We used the `DemografixeR` package to query the nationalize.io API, which provides probabilistic nationality assignments for last names based on large-scale web data [@brenninkmeijer2025, see also nationalize.io documentation]. We also collected information on country-of-origin via the Dutch Database of Surnames in the Netherlands (Nederlandse Familienamenbank), which reports the number of name bearers per surname and provides etymological notes on its origin and meaning [@centrumvoorfamiliegeschiedenis]. We combined the various signals to ISO 3166-1 alpha-2 country codes and manually filled in missing values (see our replication website for more details). Finally, we categorised country-of-origin into (1) Dutch; (2) Turkish, Surinamese, Moroccan, Dutch Antillean or (3) other. Scholars assigned to the Turkish, Surinamese, Moroccan and Dutch Antillean category are predominantly second generation migrants who followed most part of their educational career in the Netherlands. Scholars assigned to the 'other' category are mostly scholars who either joined Dutch academia as PhD student or later (cf. Tolsma...).

*Career age* was based on the publication year of the first <!--- [or second??] ---> paper of each scholar as: 2027 - year-of-first-publication.

*Position* indicates scholars’ academic rank within the Dutch university system. Starting from the free-text job titles collected from departmental staff pages, we mapped all ranks to a set of six categories: *PhD student*, *Postdoc*, *Researcher*, *Assistant professor*, *Associate professor*, and *Full professor* (including endowed, visiting and emerita).

*Discipline* indicates whether a scholar is employed at a sociology or political science department. Based on this informatin we also constructed the dyad-level variable *same-discipline* (based on possibly two university affiliations).

*University.* For each scholar we know at which of the eight university or universities he or she was employed; Radboud University (RU), Erasmus University Rotterdam (EUR), University of Amsterdam (UVA), Leiden University (LU), Vrije Universiteit Amsterdam (VU), Utrecht University (UU), Tilburg University (UVT), and University of Groningen (RUG). We also used this information to construct the dyad-level variable *same-university* (based on possibly two university affiliations). Finally, based on the primary affiliation of the scholars we constructed the *geographic-distance* dyad-levelvariable indicating the travel time in hours by public transport between the universities of the involved scholars as retrieved from 9292.nl the main public transport API for the Netherlands.

*Interdisciplinarity.* We measure the degree of research interdisciplinarity of each scholar based on the subfields scholars publish in. In OpenAlex each paper is assigned to multiple Domains, Fields, Sub-Fields and Topics (for more details see ...). Domain and Field are too broad categories to distinguish our scholars. OpenAlex distinguishes ... Topics, this we considered too fine-grained. We therefore decided to use the Sub-Field level to measure the degree of author's interdisciplinarity. Based on all harvested papers from all the authors in our sample with a publication year between 1990 and 2006, we constructed a cosine distance matrix $D$ between the different subfields $i$. This distance matrix was converted to a proximity matrix $w$ via a biweight kernel proximity function: $w_{ij} = 1 - (D_{ij}/max(D))^2$, with $i$ and $j$ indexing the different subfields. A score of 1 indicated maximum subfield similarity and 0 maximum dissimilarity. For each wave and author, we constructed a subfield profile using all author's publications in the two-year retrospective window, determining for each subfield the proportion of papers categorised as such, the subfield shares $p_i$. We then defined author interdisciplinarity (AI) as $AI = 1-  \Sigma_{ij}p_{i}*p_{j}*w_{ij}$ [@ref].

*Subfield similarity.* To assess authors' similarity in research subfields, a time-varying dyad-level variable, we followed a similar procedure. Based on the subfield profiles of the authors we once again constructed a cosine distance matrix, but now measuring the distance between authors. This distance matrix was converted to a proximity matrix. A score of 1 indicated maximum author similarity and 0 maximum dissimilarity.

*I10-index* is a time-varying variable indicating the number of articles of each author cited by at least 10 sources.

We included the variables gender, origin, career age, position, university, interdisciplinarity and i10-index at the ego (sending ties; covariate-ego) and alter (receiving ties; covariate-alter) level in our explanatory models to take into account possible individual-level differences in publication rates (and popularity as co-author) and to take into account that publication rates can vary across universities, disciplines, fields and career stages. At the dyad-level, same-discipline, same-university, and geographic-distance is included to account for collaboration opportunities; that physical proximity fosters collaboration. Same-gender, same-origin and similar career-age is included to assess choice homophily tendencies.

### RSiena

In RSiena the evolution of the network between two discretely observed time-points (or waves) is simulated via so-called ministeps. During a ministep one actor is allowed to make one tie-change; break or make one tie. The probability that a specific actor will be the next to have an opportunity to make a ministep is modelled via the rate-function. Which tie-change is most likely is modelled via the evaluation function. For the actor that is allowed to make a tie-change, the evaluation function evaluates the local network neighbourhood that would result from the tie-change under consideration. The evaluation function is constructed as a linear combination of effects (e.g. reciprocity, transitivity) and for each effect the corresponding parameter is estimated. That is, the simulation of the network evolution between time *t* and *t + 1* starts with the network at time *t* as given. The algorithm aims to optimize the user-defined rate and evaluation function in such a way that the simulated network resembles the network at time *t + 1* with respect to the effects included in evaluation function. When a parameter is positive this means that a tie change that increases the effect (e.g. the number of reciprocated ties increases in the local neighbourhood after the tie-change under consideration) is more likely than a tie-change that leaves the effect unaltered. For an easy introduction into RSiena and for a more thorough explanation of the simulation process and interpretation of the parameters see Tolsma and Hofstra 2024; chapter 7.

### Model specification

The rate-function models the speed by which the co-authorship ties change. Given that the (out)degree distribution is very skewed (see Figure ...) and our network has a clear core-periphery structure (see Figure ...), we let the rate function depend on the outdegrees. We hereby give actors with a higher outdegree more opportunity for changing her co-authorship ties.

Our main focus is, however, on the evaluation function that determines the probabilities of tie-changes. We included the baseline structural effects *density* and *reciprocity* (directed networks only). The *transitive triplets effect* is included to represent transitivity (a co-author of a co-author becomes my co-author). We also included the *three-cycles* *effect* (directed networks only) because a positive transitive triplets effect together with a negative three-cycles effect may be interpreted as a tendency toward local hierarchy, which we expect given different roles related to authorship position. We also take into account the dispersion of degrees. In the directed networks via the *in-degree popularity squared*, and *out-degree activity squared* effects. For the directed network via the

For the directed network we assume that one actor takes the initiative and proposes a new collaboration or stops an existing collaboration. If the scholar proposes a new collaboration, we assume the other scholar has to conform, otherwise the tie is not created. For stopping an existing collaboration no confirmation is required. Technically, we set the modelType option in the simulation algorithm to 3.

We start with a model including all structural effects described above and the covariate-ego and covariate-alter effects that proved relevant, and the effects by which we aim to capture collaboration opportunities. From this model, we will learn to what extent we favor women or men as co-author. We then include the effects by which we aim to assess choice homophily. In the final model, we will test our hypotheses regarding the differential impact of (social) science capital indicators (i.e. i10-index, rank, indegree popularity) across men and women by including the interactions of these indicators by the gender-alter effect.

## Results

### Descriptive statistics

#### ego-level / scholars

#### egonets

To some extent, we observe similar patterns in our data. For example, in the period 2022 and 2024, the number of distinct Dutch employed sociologists or political scientists women worked with is smaller than for men (on average 1 versus 1.3). The networks of male social scientists are also more tightly knit, as indicated by the higher clustering coefficients (Table ...). However, in contrast to previous work, we observe that among Dutch sociologists and political scientists, women are more likely than men to collaborate with scholars from universities other than one's own, as indicated by the less negative Krackhard and Stern's E-I index [@krackhardt1988] capturing the relative prevalence of between university and within university ties (see table ...). and are, thus, less locally orientated. Such descriptive statistics – of prior work and our own – however, elude the complex interdependent network dynamics from which they are the result. <!---en dus? nl anders, onze disciplines anders. mis punchline. en daarom moeten we kijken naar dynamics-->

<!---describe some--->

.

#### complete networks

some graphics as well.

### RSiena results

## Conclusion/discussion

genarative AI, future of papers/collaboration. more and more papers. instead of working with real people, with AI agentic agents? is this chance or threat to gender inequality in academica?? reduces collaboration. see paper nature 2026 Hao, q, nature 649. PD roles are shrinking the fastest?

ai might be used as compensating strategy of one lacks scientific capital in real-life collaboration networks.

Dong, 2026 proved that genai improves writing skills under specific conditions.

## References
